#!/usr/bin/env python3


import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen-name")
    
    screen_name = sys.argv[1].strip('@')

    
    tweets = helpers.get_user_timeline(screen_name, 100)
    if tweets == None:
        sys.exit("Invalid tweet")

    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    analyzer = Analyzer(positives, negatives)

    for i in range(0, len(tweets),1):
    
        score = analyzer.analyze(tweets[i])

        if score > 0.0:
            print(colored("{} {}".format(score, tweets[i]), "green"))
    
        elif score < 0.0:
            print(colored("{} {}".format(score, tweets[i]), "red"))
        
        else:
            print(colored("{} {}".format(score, tweets[i]), "yellow"))
    


if __name__ == "__main__":
    main()